// src/websocket/message-types.ts

export const MessageTypes = {
  // Client to Server
  MATCHMAKING_REQUEST: 'MATCHMAKING_REQUEST',
  PLAY_VS_COMPUTER: 'PLAY_VS_COMPUTER',
  REJOIN_GAME: 'REJOIN_GAME',
  PLAYER_ACTION: 'PLAYER_ACTION',
  CHAT_MESSAGE: 'CHAT_MESSAGE',

  // Server to Client
  MATCHMAKING_STATUS: 'MATCHMAKING_STATUS',
  GAME_START: 'GAME_START',
  GAME_STATE: 'GAME_STATE',
  PROJECTILE_UPDATE: 'PROJECTILE_UPDATE',
  EXPLOSION_EVENT: 'EXPLOSION_EVENT',
  TURN_END: 'TURN_END',
  GAME_OVER: 'GAME_OVER',
  CHAT_MESSAGE_BROADCAST: 'CHAT_MESSAGE_BROADCAST',
  PLAYER_DISCONNECT: 'PLAYER_DISCONNECT',
  ERROR: 'ERROR',
};
